global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "cadvisor"
    dns_sd_configs:
      - names:
          - "cadvisor"
        type: "A"
        port: 8080
  
  - job_name: "index_formation"
    scrape_interval: 5s
    dns_sd_configs:
      - names:
          - "index_formation"
        type: "A"
        port: 1234
  